from __future__ import annotations
import html
import re
import time
from PySide6.QtCore import QThread, Signal, Qt, QTimer
from PySide6.QtGui import QTextCursor, QTextDocument, QIcon, QPalette, QColor
from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QGridLayout, QLabel, QComboBox, QPushButton,
    QTextEdit, QTextBrowser, QMessageBox, QFrame, QDialog, QDialogButtonBox, QCheckBox
)
from .providers import ProviderFactory
from .context import ContextBuilder
from .conversations import ConversationStore
from .memory_suggestions import extract_memory_suggestions, proposal_instruction
from .planning_context import PlanningSelection, build_planning_context_result, chapter_planning_preview
from .prompting import build_system_prompt
from .quick_actions import QUICK_ACTIONS, QUICK_ACTION_BY_KEY
from ..book_memory import SECTIONS
from ..themes import THEMES
from ..ui.planning_context_dialog import PlanningContextDialog


class ProviderChatWorker(QThread):
    token = Signal(str)
    thinking = Signal(str)
    finished_ok = Signal()
    failed = Signal(str)
    cancelled = Signal()

    def __init__(self, provider, model: str, messages: list[dict], options=None):
        super().__init__()
        self.provider = provider
        self.model = model
        self.messages = messages
        self.options = options or {}
        self._stop = False

    def stop(self):
        self._stop = True
        try:
            self.provider.cancel_active()
        except Exception:
            pass

    def run(self):
        try:
            for chunk in self.provider.stream_chat(self.model, self.messages, **self.options):
                if self._stop:
                    self.cancelled.emit(); return
                if chunk.thinking: self.thinking.emit(chunk.thinking)
                if chunk.content: self.token.emit(chunk.content)
            if self._stop:
                self.cancelled.emit()
            else:
                self.finished_ok.emit()
        except Exception as exc:
            if self._stop:
                self.cancelled.emit()
            else:
                self.failed.emit(str(exc))



def markdown_to_html(text: str) -> str:
    """Return only the HTML body fragment generated by Qt Markdown.

    QTextDocument.toHtml() returns a complete HTML document with its own body
    defaults. Embedding that inside another QTextBrowser document produced
    invalid nested HTML and could preserve light/dark colours from a previous
    theme. A clean fragment inherits the card colours we set explicitly.
    """
    doc = QTextDocument()
    doc.setMarkdown(text or '')
    rendered = doc.toHtml()
    match = re.search(r'<body[^>]*>(.*)</body>', rendered, flags=re.IGNORECASE | re.DOTALL)
    return match.group(1) if match else rendered


class AIPanel(QWidget):
    """Provider-onafhankelijk AI-paneel met veilige worker-lifecycle."""
    def __init__(self, main):
        super().__init__()
        self.main = main
        self.worker = None
        self._workers = set()
        self.current_assistant = ''
        self._thinking_dots = 0
        self._thinking_base = 'Denken'
        self._final_started = False
        self._thinking_text = ''
        self._active_context = None
        self._active_user_index = None
        self._book_generation = 0
        self._book_id = None
        self._request_serial = 0
        self._active_request_id = None
        self._planning_selection = PlanningSelection()
        self._pending_memory_suggestions = []
        self.messages: list[dict] = []
        self.store = None
        self.theme_name = str(self.main.settings.value('theme','Helder') or 'Helder')

        self.thinking_timer = QTimer(self); self.thinking_timer.setInterval(350); self.thinking_timer.timeout.connect(self._animate_thinking)
        self.render_timer = QTimer(self); self.render_timer.setSingleShot(True); self.render_timer.setInterval(70); self.render_timer.timeout.connect(lambda: self._render_chat(streaming_placeholder=True))
        lay = QVBoxLayout(self); lay.setContentsMargins(14,14,14,14); lay.setSpacing(8)

        # Keep the conversation visually dominant. Persistent controls live at
        # the bottom near the composer; occasional context/quick-action tools
        # expand only when requested.
        top = QHBoxLayout()
        lab = QLabel('AI-assistent'); lab.setObjectName('sectionTitle')
        self.clear_button = QPushButton('Nieuw gesprek'); self.clear_button.setObjectName('suggestionButton'); self.clear_button.clicked.connect(self.clear_conversation)
        top.addWidget(lab); top.addStretch(); top.addWidget(self.clear_button)
        lay.addLayout(top)

        self.chat = QTextBrowser(); self.chat.setObjectName('aiChat'); self.chat.setOpenExternalLinks(True)
        lay.addWidget(self.chat, 1)

        self.thinking_button = QPushButton('Denken…'); self.thinking_button.setObjectName('thinkingButton'); self.thinking_button.clicked.connect(self._toggle_thinking_details); self.thinking_button.hide()
        self.thinking_details = QTextEdit(); self.thinking_details.setReadOnly(True); self.thinking_details.setMaximumHeight(130); self.thinking_details.setObjectName('thinkingDetails'); self.thinking_details.hide()
        lay.addWidget(self.thinking_button, 0, Qt.AlignLeft); lay.addWidget(self.thinking_details)

        self.memory_card = QFrame(); self.memory_card.setObjectName('panel'); self.memory_card.hide()
        memory_lay = QVBoxLayout(self.memory_card); memory_lay.setContentsMargins(10,8,10,8); memory_lay.setSpacing(6)
        self.memory_title = QLabel('Onthouden voor dit boek?'); self.memory_title.setObjectName('sectionTitle')
        self.memory_text = QLabel(); self.memory_text.setWordWrap(True)
        memory_actions = QHBoxLayout()
        self.memory_accept = QPushButton('Onthouden'); self.memory_accept.setObjectName('primaryButton'); self.memory_accept.clicked.connect(self._remember_suggestion)
        self.memory_edit = QPushButton('Bewerken'); self.memory_edit.clicked.connect(self._edit_suggestion)
        self.memory_ignore = QPushButton('Negeren'); self.memory_ignore.clicked.connect(self._ignore_suggestion)
        memory_actions.addWidget(self.memory_accept); memory_actions.addWidget(self.memory_edit); memory_actions.addWidget(self.memory_ignore); memory_actions.addStretch()
        self.memory_feedback = QLabel(); self.memory_feedback.setObjectName('muted'); self.memory_feedback.setWordWrap(True); self.memory_feedback.hide()
        memory_lay.addWidget(self.memory_title); memory_lay.addWidget(self.memory_text); memory_lay.addWidget(self.memory_feedback); memory_lay.addLayout(memory_actions)
        lay.addWidget(self.memory_card)

        # Collapsible context controls. Current chapter is the normal/default
        # context, so it does not permanently consume header space.
        self.context_panel = QFrame(); self.context_panel.setObjectName('panel'); self.context_panel.hide()
        context_lay = QVBoxLayout(self.context_panel); context_lay.setContentsMargins(10,8,10,8); context_lay.setSpacing(6)
        context_select_row = QHBoxLayout()
        context_select_row.addWidget(QLabel('Manuscriptcontext'))
        self.context = QComboBox(); self.context.addItems(['Huidig hoofdstuk', 'Huidige sectie', 'Hele boek']); self.context.currentTextChanged.connect(self._refresh_idle_context_summary)
        context_select_row.addWidget(self.context, 1)
        context_lay.addLayout(context_select_row)
        self.fixed_context_info = QLabel('Altijd meegestuurd: Schrijverspersona · Boekprofiel · Boekgeheugen')
        self.fixed_context_info.setObjectName('muted'); self.fixed_context_info.setWordWrap(True)
        context_lay.addWidget(self.fixed_context_info)
        self.chapter_planning_info = QLabel()
        self.chapter_planning_info.setObjectName('muted'); self.chapter_planning_info.setWordWrap(True)
        context_lay.addWidget(self.chapter_planning_info)
        self.chapter_planning_notice_row = QWidget()
        notice_lay = QHBoxLayout(self.chapter_planning_notice_row)
        notice_lay.setContentsMargins(0, 0, 0, 0)
        notice_lay.setSpacing(6)
        self.chapter_planning_notice = QLabel(
            'Nieuw: hoofdstukplanning kan meegaan met AI-vragen. Staat standaard uit. '
            'Bij een externe provider verlaten deze gegevens je computer.'
        )
        self.chapter_planning_notice.setObjectName('muted')
        self.chapter_planning_notice.setWordWrap(True)
        self.chapter_planning_notice_ack = QPushButton('Begrepen')
        self.chapter_planning_notice_ack.clicked.connect(self._acknowledge_chapter_planning_notice)
        notice_lay.addWidget(self.chapter_planning_notice, 1)
        notice_lay.addWidget(self.chapter_planning_notice_ack, 0, Qt.AlignTop)
        contains = getattr(self.main.settings, 'contains', None)
        self._chapter_planning_preference_set = bool(contains('ai_use_chapter_planning')) if callable(contains) else False
        self.chapter_planning_notice_row.setVisible(not self._chapter_planning_preference_set)
        context_lay.addWidget(self.chapter_planning_notice_row)
        self.chapter_planning_check = QCheckBox('Planning van dit hoofdstuk gebruiken')
        self.chapter_planning_check.setChecked(bool(self.main.settings.value('ai_use_chapter_planning', False, bool)))
        self.chapter_planning_check.toggled.connect(self._chapter_planning_toggled)
        context_lay.addWidget(self.chapter_planning_check)
        context_actions = QHBoxLayout()
        self.planning_context_button = QPushButton('Planning-context…'); self.planning_context_button.clicked.connect(self._choose_planning_context)
        self.context_view_button = QPushButton('Context bekijken'); self.context_view_button.clicked.connect(self._show_context_dialog)
        context_actions.addWidget(self.planning_context_button); context_actions.addWidget(self.context_view_button); context_actions.addStretch()
        context_lay.addLayout(context_actions)
        lay.addWidget(self.context_panel)

        # Quick actions are useful, but should not permanently steal vertical
        # writing/chat space. They can start expanded through AI settings.
        self.quick_panel = QFrame(); self.quick_panel.setObjectName('panel')
        quick_lay = QVBoxLayout(self.quick_panel); quick_lay.setContentsMargins(10,8,10,8); quick_lay.setSpacing(5)
        quick_label = QLabel('Snelacties'); quick_label.setObjectName('microLabel')
        quick_lay.addWidget(quick_label)
        self.quick_action_buttons = {}
        quick_grid = QGridLayout(); quick_grid.setContentsMargins(0,0,0,0); quick_grid.setHorizontalSpacing(6); quick_grid.setVerticalSpacing(4)
        for index, action in enumerate(QUICK_ACTIONS):
            button = QPushButton(action.label); button.setObjectName('suggestionButton')
            button.setToolTip(action.tooltip); button.setAccessibleName(action.label)
            button.clicked.connect(lambda _checked=False, key=action.key: self._apply_quick_action(key))
            quick_grid.addWidget(button, index // 2, index % 2)
            self.quick_action_buttons[action.key] = button
        quick_lay.addLayout(quick_grid)
        self.quick_panel.setVisible(bool(self.main.settings.value('ai_quick_actions_expanded', False, bool)))
        lay.addWidget(self.quick_panel)

        self.input = QTextEdit(); self.input.setObjectName('aiInput'); self.input.setMaximumHeight(108); self.input.setPlaceholderText('Stel een vraag over je tekst…')
        self.action_button = QPushButton(); self.action_button.setObjectName('aiActionButton')
        self.action_button.setFixedSize(38, 38)
        self.action_button.clicked.connect(self._action_clicked)
        self._set_action_state(False)
        compose = QHBoxLayout(); compose.setContentsMargins(0,0,0,0); compose.setSpacing(8)
        compose.addWidget(self.input, 1); compose.addWidget(self.action_button, 0, Qt.AlignBottom)
        lay.addLayout(compose)

        tools = QHBoxLayout(); tools.setContentsMargins(0,0,0,0); tools.setSpacing(6)
        self.context_toggle = QPushButton('Context'); self.context_toggle.setObjectName('suggestionButton'); self.context_toggle.setCheckable(True); self.context_toggle.clicked.connect(self._toggle_context_controls)
        self.quick_toggle = QPushButton('Snelacties'); self.quick_toggle.setObjectName('suggestionButton'); self.quick_toggle.setCheckable(True); self.quick_toggle.setChecked(self.quick_panel.isVisible()); self.quick_toggle.clicked.connect(self._toggle_quick_actions)
        tools.addWidget(self.context_toggle); tools.addWidget(self.quick_toggle); tools.addStretch()
        lay.addLayout(tools)
        self._refresh_idle_context_summary()
        self._update_busy_buttons()

    def is_busy(self) -> bool:
        return bool(self.worker and self.worker.isRunning())

    def _icon_path(self, name: str):
        from pathlib import Path
        return str(Path(__file__).resolve().parents[1] / 'icons' / f'{name}.svg')

    def _set_action_state(self, busy: bool):
        self.action_button.setIcon(QIcon(self._icon_path('stop' if busy else 'send')))
        self.action_button.setToolTip('Stop AI' if busy else 'Versturen')
        self.action_button.setAccessibleName('Stop AI' if busy else 'Versturen')

    def _action_clicked(self):
        if self.is_busy():
            self.stop_ai()
        else:
            self.send()

    def _has_manuscript_selection(self) -> bool:
        editor_page = getattr(self.main, 'editor_page', None)
        editor = getattr(editor_page, 'editor', None) if editor_page is not None else None
        return bool(editor and editor.textCursor().hasSelection())

    def refresh_quick_actions(self):
        busy = self.is_busy()
        has_selection = self._has_manuscript_selection()
        for action in QUICK_ACTIONS:
            button = self.quick_action_buttons.get(action.key)
            if not button:
                continue
            enabled = not busy and (has_selection or not action.requires_selection)
            button.setEnabled(enabled)
            if action.requires_selection and not has_selection:
                button.setToolTip('Selecteer eerst tekst in het manuscript.')
            else:
                button.setToolTip(action.tooltip)

    def _apply_quick_action(self, key: str):
        action = QUICK_ACTION_BY_KEY.get(key)
        if not action or self.is_busy():
            return
        if action.requires_selection and not self._has_manuscript_selection():
            self.refresh_quick_actions()
            return
        self.input.setPlainText(action.prompt)
        cursor = self.input.textCursor(); cursor.movePosition(QTextCursor.End); self.input.setTextCursor(cursor)
        self.input.setFocus()

    def _update_busy_buttons(self):
        busy=self.is_busy()
        self.action_button.setEnabled(True)
        self._set_action_state(busy)
        self.clear_button.setEnabled(not busy)
        has_book = self.store is not None
        self.planning_context_button.setEnabled(not busy and has_book)
        preview = self._chapter_planning_preview() if has_book else None
        self.chapter_planning_check.setEnabled(bool(preview and preview.text and not preview.error and not busy))
        self.refresh_quick_actions()

    def set_book(self, book):
        new_book_id = getattr(book, 'id', None) if book is not None else None
        if book is not None and new_book_id == self._book_id:
            # Conflict resolution/version restore may replace the live Book
            # object while keeping the same logical book. Keep an in-flight AI
            # request and its unsaved user message alive; only repoint storage
            # at the newly adopted live path.
            self.store = ConversationStore(book)
            return

        # Invalidate every callback that belongs to the previously visible book
        # before retiring an old worker. QThread signals are queued to the GUI
        # thread, so they may arrive only after this method has already swapped
        # self.store/self.messages to another book.
        self._book_generation += 1
        self._book_id = new_book_id
        self._planning_selection = PlanningSelection()
        self._pending_memory_suggestions = []
        self.memory_card.hide()
        self._active_request_id = None
        old_worker = self.worker
        if old_worker is not None and old_worker.isRunning():
            old_worker.stop()
        # Do not block the GUI waiting for a provider/network call to honour
        # cancellation. The old worker remains strongly referenced in
        # self._workers until its finished signal arrives, but it is no longer
        # the active worker for the newly selected book.
        self.worker = None

        self.render_timer.stop()
        self._finish_thinking()
        self.current_assistant = ''
        self._final_started = False
        self._active_context = None
        self._active_user_index = None
        self.store = ConversationStore(book) if book else None
        self.messages = self.store.load() if self.store else []
        self.context.setCurrentText('Huidig hoofdstuk')
        self.context_panel.hide(); self.context_toggle.setChecked(False)
        self._refresh_idle_context_summary()
        self._render_chat()
        self._update_busy_buttons()

    def _choose_planning_context(self):
        book = self.main.active_book()
        if not book or self.is_busy():
            return
        dialog = PlanningContextDialog(self, self.main.library, book, self._planning_selection)
        if dialog.exec() == QDialog.Accepted:
            self._planning_selection = dialog.selection()
            self._refresh_idle_context_summary()

    def _planning_context_result(self):
        return build_planning_context_result(self.main.library, self.main.active_book(), self._planning_selection)

    def _planning_context(self):
        result = self._planning_context_result()
        return result.text, result.labels

    def _active_live_chapter_id(self):
        page = getattr(self.main, 'editor_page', None)
        if page is None or not page.chapter_context_available():
            return None
        chapter = getattr(page, 'chapter', None)
        return getattr(chapter, 'id', None) if chapter is not None else None

    def _chapter_planning_preview(self):
        return chapter_planning_preview(
            self.main.library, self.main.active_book(), self._active_live_chapter_id()
        )


    def _acknowledge_chapter_planning_notice(self):
        self.main.settings.setValue('ai_use_chapter_planning', False)
        self._chapter_planning_preference_set = True
        if hasattr(self, 'chapter_planning_notice_row'):
            self.chapter_planning_notice_row.hide()
        self._refresh_idle_context_summary()

    def _chapter_planning_toggled(self, checked: bool):
        self.main.settings.setValue('ai_use_chapter_planning', bool(checked))
        self._chapter_planning_preference_set = True
        if hasattr(self, 'chapter_planning_notice_row'):
            self.chapter_planning_notice_row.hide()
        self._refresh_idle_context_summary()

    def _active_chapter_planning_text(self) -> str:
        preview = self._chapter_planning_preview()
        if preview.error or not preview.text or not self.chapter_planning_check.isChecked():
            return ''
        return preview.text

    def refresh_context_summary(self):
        self._refresh_idle_context_summary()

    def _refresh_idle_context_summary(self, *_args):
        result = self._planning_context_result()
        labels = result.labels
        mode = self.context.currentText()
        custom = mode != 'Huidig hoofdstuk' or bool(labels)
        if result.error:
            self.context_toggle.setText('Context · Planning niet beschikbaar')
        else:
            self.context_toggle.setText('Context · aangepast' if custom else 'Context')
        details = [mode]
        if result.error:
            details.append(result.error)
        elif labels:
            details.append('Planning-context: ' + ', '.join(labels))
        self.context_toggle.setToolTip(' · '.join(details))

        preview = self._chapter_planning_preview()
        available = bool(preview.text and not preview.error)
        self.chapter_planning_check.setEnabled(available and not self.is_busy())
        if preview.error:
            self.chapter_planning_info.setText('Planning van dit hoofdstuk: niet beschikbaar — ' + preview.error)
        elif preview.labels and preview.text:
            label_text = ' · '.join(preview.labels)
            status = 'wordt meegestuurd' if self.chapter_planning_check.isChecked() else 'niet meegestuurd'
            self.chapter_planning_info.setText(f'Planning van dit hoofdstuk: {label_text} · {status}')
        else:
            self.chapter_planning_info.setText('Planning van dit hoofdstuk: geen gekoppelde scènes')

    def _toggle_context_controls(self, checked=False):
        visible = bool(checked)
        self.context_panel.setVisible(visible)
        if visible and self.quick_panel.isVisible():
            self.quick_panel.hide(); self.quick_toggle.setChecked(False)

    def _toggle_quick_actions(self, checked=False):
        visible = bool(checked)
        self.quick_panel.setVisible(visible)
        if visible and self.context_panel.isVisible():
            self.context_panel.hide(); self.context_toggle.setChecked(False)

    def apply_settings(self):
        """Apply AI-panel presentation settings without rebuilding the panel."""
        expanded = bool(self.main.settings.value('ai_quick_actions_expanded', False, bool))
        self.quick_panel.setVisible(expanded)
        self.quick_toggle.setChecked(expanded)
        if expanded:
            self.context_panel.hide(); self.context_toggle.setChecked(False)


    @staticmethod
    def _compact_planning_display(text: str) -> str:
        """Keep Planning previews readable without changing prompt text."""
        return (text or '').replace('\n\n- ', '\n- ')

    def _show_context_dialog(self):
        builder = ContextBuilder(self.main)
        context = builder.build(self.context.currentText())
        planning = self._planning_context_result()
        chapter_preview = self._chapter_planning_preview()
        lines = [
            'Vaste context: Schrijverspersona · Boekprofiel · Boekgeheugen',
            f'Manuscriptcontext: {context.label}',
        ]
        if planning.error:
            lines.extend(['', planning.error])
        elif planning.labels:
            lines.extend(['', 'Geselecteerde Planning-context:', self._compact_planning_display(planning.text)])
        else:
            lines.extend(['', 'Planning-context: niet geselecteerd'])

        chapter_status = 'wordt meegestuurd' if (self.chapter_planning_check.isChecked() and chapter_preview.text and not chapter_preview.error) else 'wordt niet meegestuurd'
        lines.extend(['', f'Planning van huidig hoofdstuk — {chapter_status}:'])
        if chapter_preview.error:
            lines.append(chapter_preview.error)
        elif chapter_preview.text:
            lines.append(self._compact_planning_display(chapter_preview.text))
        else:
            lines.append('[geen gekoppelde scènes]')
        dialog = QDialog(self)
        dialog.setWindowTitle('AI-context bekijken')
        dialog.resize(620, 460)
        lay = QVBoxLayout(dialog)
        view = QTextEdit(); view.setReadOnly(True); view.setPlainText('\n'.join(lines))
        buttons = QDialogButtonBox(QDialogButtonBox.Close)
        buttons.rejected.connect(dialog.reject)
        lay.addWidget(view, 1); lay.addWidget(buttons)
        dialog.exec()

    def _show_memory_suggestion(self):
        if not self._pending_memory_suggestions:
            self.memory_card.hide()
            return
        suggestion = self._pending_memory_suggestions[0]
        category = self._memory_section_title(suggestion.section_key)
        count = len(self._pending_memory_suggestions)
        suffix = f' · {count} voorstellen' if count > 1 else ''
        self.memory_title.setText(f'Onthouden voor dit boek? · {category}{suffix}')
        self.memory_text.setText(suggestion.text)
        self.memory_feedback.clear(); self.memory_feedback.hide()
        self.memory_card.show()

    def _memory_section_title(self, section_key: str) -> str:
        section = next((section for section in SECTIONS if section.key == section_key), None)
        return section.title if section else section_key

    def _append_chat_notice(self, text: str):
        """Add a local QuietWriter confirmation to the visible chat.

        Notice messages are persisted with the conversation so the confirmation
        remains visible after reopening the book, but they are deliberately
        excluded from provider context (only user/assistant roles are sent).
        """
        self.messages.append(ConversationStore.entry('notice', text))
        if self.store:
            self.store.save(self.messages)
        self._render_chat()

    def _persist_memory_suggestion(self, section_key: str, text: str) -> bool:
        book = self.main.active_book()
        if not book:
            self.memory_feedback.setText('Niet opgeslagen: er is geen actief boek.')
            self.memory_feedback.show()
            return False
        page = self.main.book_memory_page
        try:
            # The AI action must not silently depend on whether the Book memory
            # page happened to be opened before. Rebind it to the active live
            # book first; adopt_book preserves any same-book pending edits.
            if page.book is None or page.book.id != book.id:
                if page.adopt_book(book) is False:
                    raise RuntimeError('Boekgeheugen kon niet aan het actieve boek worden gekoppeld.')
            ok = page.add_suggestion(section_key, text)
        except Exception as exc:
            ok = False
            self.memory_feedback.setText(f'Niet opgeslagen: {exc}')
            self.memory_feedback.show()
        if not ok:
            if not self.memory_feedback.text():
                self.memory_feedback.setText('Niet opgeslagen. Controleer Boekgeheugen of probeer opnieuw.')
                self.memory_feedback.show()
            return False
        self.main.status.showMessage('Opgeslagen in Boekgeheugen.', 4000)
        return True

    def _remember_suggestion(self):
        if not self._pending_memory_suggestions:
            return
        suggestion = self._pending_memory_suggestions[0]
        if not self._persist_memory_suggestion(suggestion.section_key, suggestion.text):
            return
        self._append_chat_notice(
            f'Opgeslagen in Boekgeheugen · {self._memory_section_title(suggestion.section_key)}'
        )
        self._pending_memory_suggestions.pop(0)
        self._show_memory_suggestion()

    def _ignore_suggestion(self):
        if self._pending_memory_suggestions:
            self._pending_memory_suggestions.pop(0)
        self._show_memory_suggestion()

    def _edit_suggestion(self):
        if not self._pending_memory_suggestions:
            return
        suggestion = self._pending_memory_suggestions[0]
        dialog = QDialog(self); dialog.setWindowTitle('Geheugenvoorstel bewerken'); dialog.resize(520, 330)
        lay = QVBoxLayout(dialog)
        category = QComboBox()
        for section in SECTIONS:
            category.addItem(section.title, section.key)
        idx = category.findData(suggestion.section_key)
        category.setCurrentIndex(max(0, idx))
        edit = QTextEdit(); edit.setPlainText(suggestion.text); edit.setAcceptRichText(False)
        lay.addWidget(QLabel('Categorie')); lay.addWidget(category); lay.addWidget(QLabel('Tekst')); lay.addWidget(edit, 1)
        buttons = QDialogButtonBox(QDialogButtonBox.Save | QDialogButtonBox.Cancel)
        buttons.button(QDialogButtonBox.Save).setText('Onthouden'); buttons.button(QDialogButtonBox.Cancel).setText('Annuleren')
        buttons.accepted.connect(dialog.accept); buttons.rejected.connect(dialog.reject); lay.addWidget(buttons)
        if dialog.exec() != QDialog.Accepted:
            return
        text = edit.toPlainText().strip()
        if not text:
            return
        section_key = str(category.currentData())
        if self._persist_memory_suggestion(section_key, text):
            self._append_chat_notice(
                f'Opgeslagen in Boekgeheugen · {self._memory_section_title(section_key)}'
            )
            self._pending_memory_suggestions.pop(0)
            self._show_memory_suggestion()

    def clear_conversation(self):
        if self.is_busy(): return
        self.messages = []
        if self.store: self.store.save(self.messages)
        self._render_chat()

    def _provider_model(self):
        provider = ProviderFactory.from_settings(self.main.settings)
        pname = str(self.main.settings.value('ai_provider', 'ollama') or 'ollama').lower()
        key = 'openrouter_model' if pname == 'openrouter' else 'ollama_model'
        return provider, str(self.main.settings.value(key, '') or '')

    def send(self):
        prompt = self.input.toPlainText().strip()
        if not prompt or self.is_busy(): return
        provider, model = self._provider_model()
        if not model:
            QMessageBox.information(self, 'AI', 'Kies eerst een AI-model in Instellingen.'); return
        if not provider.is_available():
            QMessageBox.warning(self, 'AI', 'De geselecteerde AI-provider is niet bereikbaar of niet geconfigureerd.'); return

        builder = ContextBuilder(self.main)
        manuscript_context = builder.build(self.context.currentText())
        planning = self._planning_context_result()
        if planning.error:
            manuscript_context.pieces.append('Planning niet beschikbaar — ' + planning.error)
        elif planning.labels:
            manuscript_context.pieces.append('Planning: ' + ', '.join(planning.labels))
        chapter_planning_text = self._active_chapter_planning_text()
        if chapter_planning_text:
            manuscript_context.pieces.append('Planning van huidig hoofdstuk: meegestuurd')
        self.input.clear()
        self._continue_send(provider, model, prompt, manuscript_context, planning.text, chapter_planning_text)


    def _continue_send(self, provider, model: str, prompt: str, context, planning_text: str = '', chapter_planning_text: str = ''):
        self._active_context = context
        self._refresh_idle_context_summary()
        persona=self.main.library.read_persona()
        active_book = self.main.active_book()
        book_profile = self.main.library.read_book_profile(active_book) if active_book else ''
        book_memory = self.main.library.read_book_memory(active_book) if active_book else ''
        context_text=context.text

        system_prompt = build_system_prompt(
            persona=persona,
            book_profile=book_profile,
            book_memory=book_memory,
            planning_text=planning_text,
            chapter_planning_text=chapter_planning_text,
            context_label=context.label,
            context_text=context_text,
        )

        self.messages.append(ConversationStore.entry('user', prompt, {'pieces': context.pieces, 'scope': self.context.currentText()}))
        self._active_user_index=len(self.messages)-1
        self.current_assistant=''; self._final_started=False; self._thinking_text=''
        thinking_requested = bool(self.main.settings.value('ai_disable_thinking', False, bool))
        provider_name = str(getattr(provider, 'name', '') or '')
        capability = str(self.main.settings.value(
            f'ai_thinking_can_disable/{provider_name}/{model}', 'unknown'
        ) or 'unknown').lower()
        # A checked but disabled UI control must never force an unsupported
        # provider parameter. Unknown/capability-only models may still receive
        # the best-effort request exactly as before.
        thinking_disabled = thinking_requested and capability != 'false'
        self._render_chat(streaming_placeholder=True); self._start_thinking('AI werkt' if thinking_disabled else 'Denken')

        # Eenvoudige, directe chatflow. Geen tokenberekeningen, geen automatische
        # contextvensters en geen provider-specifieke tuning. QuietWriter stuurt
        # alleen persona + boekprofiel + boekgeheugen + optionele hoofdstukplanning + optionele gerichte Planning-context + gekozen manuscriptcontext + een beperkte recente chat
        # naar het geselecteerde model. De provider/modelruntime bepaalt de context.
        recent=[{'role':m['role'],'content':m['content']} for m in self.messages[-6:] if m.get('role') in {'user','assistant'}]
        messages=[{'role':'system','content':system_prompt}] + recent
        self._request_serial += 1
        request_id = (self._book_generation, self._request_serial)
        provider_options = {}
        if thinking_disabled:
            if getattr(provider, 'name', '') == 'ollama':
                provider_options['think'] = False
            elif getattr(provider, 'name', '') == 'openrouter':
                provider_options['reasoning'] = {'enabled': False}
        worker = ProviderChatWorker(provider,model,messages,options=provider_options)
        self.worker = worker
        self._workers.add(worker)
        self._active_request_id = request_id
        worker.token.connect(lambda text, w=worker, rid=request_id: self._token(w, rid, text))
        worker.thinking.connect(lambda text, w=worker, rid=request_id: self._thinking(w, rid, text))
        worker.failed.connect(lambda err, w=worker, rid=request_id: self._fail(w, rid, err))
        worker.finished_ok.connect(lambda w=worker, rid=request_id: self._done(w, rid))
        worker.cancelled.connect(lambda w=worker, rid=request_id: self._chat_cancelled(w, rid))
        worker.finished.connect(lambda w=worker, rid=request_id: self._chat_thread_finished(w, rid))
        worker.start(); self._update_busy_buttons()

    def stop_ai(self):
        if self.worker and self.worker.isRunning():
            self.worker.stop()
            self.action_button.setEnabled(False)
            self._thinking_base = 'Stoppen'
            self.thinking_button.setText('Stoppen…')

    def _wait_for_workers(self, timeout_ms=3000) -> bool:
        running = [worker for worker in self._workers if worker.isRunning()]
        if not running:
            return True
        deadline = time.monotonic() + max(0, timeout_ms) / 1000.0
        for worker in running:
            remaining_ms = max(0, int((deadline - time.monotonic()) * 1000))
            if remaining_ms <= 0 or not worker.wait(remaining_ms):
                return False
        return not any(worker.isRunning() for worker in self._workers)

    def shutdown(self, timeout_ms=4000) -> bool:
        # A book switch may leave a cancelled network worker finishing in the
        # background. Stop every retained worker before Qt destroys the panel.
        for worker in list(self._workers):
            if worker.isRunning():
                worker.stop()
        return self._wait_for_workers(timeout_ms)

    def _start_thinking(self, base='Denken'):
        self._thinking_base=base; self._thinking_dots = 0
        self.thinking_details.clear(); self.thinking_details.hide()
        self.thinking_button.setText(base+'…'); self.thinking_button.show(); self.thinking_timer.start()

    def _animate_thinking(self):
        self._thinking_dots = (self._thinking_dots + 1) % 4
        self.thinking_button.setText(self._thinking_base + '.' * (self._thinking_dots + 1))

    def _toggle_thinking_details(self):
        if self._thinking_text.strip(): self.thinking_details.setVisible(not self.thinking_details.isVisible())

    def _request_is_current(self, worker, request_id) -> bool:
        return bool(
            worker is self.worker
            and request_id == self._active_request_id
            and request_id[0] == self._book_generation
        )

    def _thinking(self, worker, request_id, text):
        if not self._request_is_current(worker, request_id):
            return
        self._thinking_text += text
        self.thinking_details.setPlainText(self._thinking_text)
        cur = self.thinking_details.textCursor(); cur.movePosition(QTextCursor.End); self.thinking_details.setTextCursor(cur)

    def _finish_thinking(self):
        self.thinking_timer.stop(); self.thinking_details.clear(); self.thinking_details.hide(); self.thinking_button.hide(); self._thinking_text = ''

    def _token(self, worker, request_id, text):
        if not self._request_is_current(worker, request_id):
            return
        if not self._final_started:
            self._final_started = True; self._finish_thinking()
        self.current_assistant += text
        if not self.render_timer.isActive(): self.render_timer.start()

    def _done(self, worker, request_id):
        if not self._request_is_current(worker, request_id):
            return
        self._finish_thinking()
        if self.current_assistant.strip():
            context = self._active_context
            visible, suggestions = extract_memory_suggestions(self.current_assistant)
            if visible:
                self.messages.append(ConversationStore.entry('assistant', visible, {'pieces': context.pieces if context else []}))
            if self.store: self.store.save(self.messages)
            if suggestions:
                self._pending_memory_suggestions.extend(suggestions)
                self._show_memory_suggestion()
        self._active_user_index=None
        self.render_timer.stop(); self.current_assistant = ''; self._render_chat()

    def _fail(self, worker, request_id, err):
        if not self._request_is_current(worker, request_id):
            return
        self._finish_thinking(); self.current_assistant=''
        self.messages.append(ConversationStore.entry('assistant', f'Fout: {err}'))
        self._active_user_index=None
        if self.store: self.store.save(self.messages)
        self._render_chat()

    def _chat_cancelled(self, worker, request_id):
        if not self._request_is_current(worker, request_id):
            return
        self._finish_thinking(); self.render_timer.stop(); self.current_assistant=''
        # Een gestopte opdracht wordt niet als half gesprek bewaard.
        if self._active_user_index is not None and self._active_user_index == len(self.messages)-1:
            if self.messages[self._active_user_index].get('role') == 'user':
                self.messages.pop()
        self._active_user_index=None
        self._refresh_idle_context_summary()
        self._render_chat()

    def _chat_thread_finished(self, worker, request_id):
        # Een oude worker mag nooit een inmiddels nieuwere worker-reference
        # wissen. Dit kan gebeuren wanneer zijn queued finished-signaal pas na
        # een boekwissel (of een nieuwe aanvraag) door de GUI-thread wordt verwerkt.
        if self.worker is worker:
            self.worker = None
            if self._active_request_id == request_id:
                self._active_request_id = None
        self._workers.discard(worker)
        worker.deleteLater()
        self._update_busy_buttons()

    def apply_theme(self, theme_name: str):
        """Re-render rich chat content for the active QuietWriter theme."""
        self.theme_name = theme_name if theme_name in THEMES else 'Helder'
        theme = THEMES[self.theme_name]
        # QTextBrowser can otherwise retain its HTML document base brush across
        # a global QSS switch. Set the palette as well as rebuilding the HTML.
        palette = self.chat.palette()
        palette.setColor(QPalette.Base, QColor(theme['panel']))
        palette.setColor(QPalette.Text, QColor(theme['text']))
        self.chat.setPalette(palette)
        self._render_chat(streaming_placeholder=bool(self.current_assistant))

    def _render_chat(self, streaming_placeholder=False):
        theme = THEMES.get(self.theme_name, THEMES['Helder'])
        user_bg = theme['accent_soft']
        ai_bg = theme['panel2']
        text = theme['text']
        muted = theme['muted']
        blocks=[]
        for msg in self.messages:
            role = msg.get('role'); content = msg.get('content','')
            if role == 'user':
                body = html.escape(content).replace('\n','<br>')
                blocks.append(
                    f'<div align="right"><table width="86%" cellspacing="0" cellpadding="10" bgcolor="{user_bg}">'
                    f'<tr><td style="color:{text};"><span style="color:{muted}; font-size:10px; font-weight:600;">JIJ</span><br>{body}</td></tr></table></div><br>'
                )
            elif role == 'notice':
                body = html.escape(content).replace('\n','<br>')
                blocks.append(
                    f'<div align="left" style="margin:2px 8px 8px 8px; color:{muted}; font-size:11px;">'
                    f'<b>QuietWriter</b> · {body}</div>'
                )
            else:
                body = markdown_to_html(content)
                blocks.append(
                    f'<div align="left"><table width="96%" cellspacing="0" cellpadding="10" bgcolor="{ai_bg}">'
                    f'<tr><td style="color:{text};"><span style="color:{muted}; font-size:10px; font-weight:600;">QUIETWRITER</span><br><div style="color:{text};">{body}</div></td></tr></table></div><br>'
                )
        if streaming_placeholder and self.current_assistant:
            stream_text = self.current_assistant
            marker_at = stream_text.find('[[QW_MEMORY|')
            if marker_at >= 0:
                stream_text = stream_text[:marker_at].rstrip()
            if stream_text:
                body = markdown_to_html(stream_text)
                blocks.append(
                    f'<div align="left"><table width="96%" cellspacing="0" cellpadding="10" bgcolor="{ai_bg}">'
                    f'<tr><td style="color:{text};"><span style="color:{muted}; font-size:10px; font-weight:600;">QUIETWRITER</span><br><div style="color:{text};">{body}</div></td></tr></table></div><br>'
                )
        self.chat.setHtml(f'<html><body style="margin:4px; background:{theme["panel"]}; color:{text};">' + ''.join(blocks) + '</body></html>')
        cur=self.chat.textCursor(); cur.movePosition(QTextCursor.End); self.chat.setTextCursor(cur)

